# ==============================================================================
#  Copyright 2019 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ==============================================================================

workspace(name = "ngraph_bridge")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load("@//tf_configure:tf_configure.bzl", "tf_configure")
tf_configure(
    name = "local_config_tf",
)

# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's WORKSPACE file.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "a38539c5b5c358548e75b44141b4ab637bba7c4dc02b46b1f62a96d6433f56ae",
    strip_prefix = "rules_closure-dbb96841cc0a5fb2664c37822803b06dab20c7d1",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz",  # 2018-04-13
    ],
)

http_archive(
    name = "org_tensorflow",
    sha256 = "7cd19978e6bc7edc2c847bce19f95515a742b34ea5e28e4389dade35348f58ed",
    strip_prefix = "tensorflow-1.13.1",
    urls = [
        "http://mirror.tensorflow.org/github.com/tensorflow/tensorflow/archive/v1.13.1.tar.gz",
        "https://github.com/tensorflow/tensorflow/archive/v1.13.1.tar.gz",
    ],
)
load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace(path_prefix = "", tf_repo_name = "org_tensorflow")

http_archive(
    name = "ngraph",
    build_file = "//:bazel/ngraph.BUILD",
    sha256 = "e3b448fb1329b8cf544b3eee2f82656e5b9d60f94fbdaa3448afd20475786a87",
    strip_prefix = "ngraph-0.20.0-rc.0",
    urls = [
        "https://mirror.bazel.build/github.com/NervanaSystems/ngraph/archive/v0.20.0-rc.0-rc.0.tar.gz",
        "https://github.com/NervanaSystems/ngraph/archive/v0.20.0-rc.0.tar.gz"
    ],
)

http_archive(
    name = "nlohmann_json_lib",
    build_file = "//:bazel/nlohmann_json.BUILD",
    sha256 = "e0b1fc6cc6ca05706cce99118a87aca5248bd9db3113e703023d23f044995c1d",
    strip_prefix = "json-3.5.0",
    urls = [
        "https://mirror.bazel.build/github.com/nlohmann/json/archive/v3.5.0.tar.gz",
        "https://github.com/nlohmann/json/archive/v3.5.0.tar.gz",
    ],
)

http_archive(
        name = "tbb",
        build_file = "//:bazel/tbb.BUILD",
        sha256 = "c3245012296f09f1418b78a8c2f17df5188b3bd0db620f7fd5fabe363320805a",
        strip_prefix = "tbb-2019_U1",
        urls = [
            "http://mirror.tensorflow.org/github.com/01org/tbb/archive/2019_U1.zip",
            "https://github.com/01org/tbb/archive/2019_U1.zip",
        ],
    )

http_archive(
        name = "eigen",
        build_file = "//:bazel/eigen.BUILD",
        sha256 = "74845ea27e19a1bcf63f3f271de62e06798f23e0467bb9d45b83a94918941b23",
        strip_prefix = "eigen-eigen-20cbc6576426",
        urls = [
            "http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/20cbc6576426.tar.gz",
            "https://bitbucket.org/eigen/eigen/get/20cbc6576426.tar.gz",
        ],
    )

http_archive(
        name = "mkl_dnn",
        build_file = "//:bazel/mkl_dnn.BUILD",
        sha256 = "38a1c02104ee9f630c1ad68164119cd58ad0aaf59e04ccbe7bd5781add7bfbea",
        strip_prefix = "mkl-dnn-0.18",
        urls = [
            "http://mirror.tensorflow.org/github.com/intel/mkl-dnn/archive/v0.18.tar.gz",
            "https://github.com/intel/mkl-dnn/archive/v0.18.tar.gz",
        ],
    )

http_archive(
        name = "mkl_linux",
        build_file = "//:bazel/mkl.BUILD",
        sha256 = "f4129843d5c2996419f96f10928edd02b2150998861a088dc7cfa1b6a058102a",
        strip_prefix = "mklml_lnx_2019.0.3.20190220",
        urls = [
            "http://mirror.tensorflow.org/github.com/intel/mkl-dnn/releases/download/v0.18/mklml_lnx_2019.0.3.20190220.tgz",
            "https://github.com/intel/mkl-dnn/releases/download/v0.18/mklml_lnx_2019.0.3.20190220.tgz",
        ],
    )