node {
  name: "CombinedNonMaxSuppression"
  op: "CombinedNonMaxSuppression"
  input: "arg_0"
  input: "arg_1"
  input: "arg_2"
  input: "arg_3"
  input: "arg_4"
  input: "arg_5"
  attr {
    key: "clip_boxes"
    value {
      b: true
    }
  }
  attr {
    key: "pad_per_class"
    value {
      b: false
    }
  }
}
node {
  name: "arg_0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape{
        dim {
          size: 10
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 4
        }
      }
    }
  }
}
node {
  name: "arg_1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape{
        dim {
          size: 10
        }
        dim {
          size: 2
        }
        dim {
          size: 20
        }
      }
    }
  }
}
node {
  name: "arg_2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape{
      }
    }
  }
}
node {
  name: "arg_3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape{
      }
    }
  }
}
node {
  name: "arg_4"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape{
      }
    }
  }
}
node {
  name: "arg_5"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape{
      }
    }
  }
}
library {
}
versions {
  producer: 29
}
